import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

interface EnhanceRequest {
  problem: string;
  solution: string;
  impact: string;
}

interface EnhanceResponse {
  enhanced_problem: string;
  enhanced_solution: string;
  enhanced_impact: string;
}

interface ErrorResponse {
  error: string;
  code: string;
}

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
const GEMINI_API_URL =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent';

/**
 * Retry wrapper with exponential backoff
 * Implements retry logic: 1s, 2s, 4s delays (AC: 4)
 */
async function withRetry<T>(
  fn: () => Promise<T>,
  maxRetries: number = 3,
  baseDelay: number = 1000
): Promise<T> {
  let lastError: Error | null = null;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error as Error;
      console.error(`Attempt ${attempt + 1} failed:`, error);

      if (attempt < maxRetries - 1) {
        const delay = baseDelay * Math.pow(2, attempt);
        await new Promise((resolve) => setTimeout(resolve, delay));
      }
    }
  }

  throw lastError;
}

/**
 * Call Gemini API to enhance idea content
 * Returns enhanced problem, solution, and impact (AC: 1, 3)
 */
async function enhanceWithGemini(
  problem: string,
  solution: string,
  impact: string
): Promise<EnhanceResponse> {
  const prompt = `You are a professional business analyst helping to improve idea clarity and professionalism.

Enhance the following idea submission by:
1. Improving clarity and readability
2. Making it more professional and structured
3. Preserving the original intent and meaning
4. Adding context where helpful
5. Using concise, impactful language

IMPORTANT: Return ONLY a valid JSON object with the enhanced text for each field. Do not include any markdown, code blocks, or explanatory text.

Original Idea:

PROBLEM:
${problem}

SOLUTION:
${solution}

IMPACT:
${impact}

Return your response in this exact JSON format (no markdown, no code blocks):
{"enhanced_problem": "...", "enhanced_solution": "...", "enhanced_impact": "..."}`;

  const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: prompt }],
        },
      ],
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 2048,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Gemini API error:', response.status, errorText);
    throw new Error(`Gemini API error: ${response.status}`);
  }

  const data = await response.json();

  // Extract text from Gemini response
  const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText) {
    throw new Error('No content generated by Gemini');
  }

  // Parse JSON from response (handle potential markdown code blocks)
  let cleanedText = generatedText.trim();

  // Remove markdown code blocks if present
  if (cleanedText.startsWith('```json')) {
    cleanedText = cleanedText.slice(7);
  } else if (cleanedText.startsWith('```')) {
    cleanedText = cleanedText.slice(3);
  }
  if (cleanedText.endsWith('```')) {
    cleanedText = cleanedText.slice(0, -3);
  }
  cleanedText = cleanedText.trim();

  try {
    const enhanced = JSON.parse(cleanedText) as EnhanceResponse;

    // Validate response structure
    if (!enhanced.enhanced_problem || !enhanced.enhanced_solution || !enhanced.enhanced_impact) {
      throw new Error('Invalid response structure from Gemini');
    }

    return enhanced;
  } catch (parseError) {
    console.error('Failed to parse Gemini response:', cleanedText);
    throw new Error('Failed to parse AI response');
  }
}

serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { 
      status: 200,
      headers: corsHeaders 
    });
  }

  try {
    // Validate API key is configured (AC: 2)
    if (!GEMINI_API_KEY) {
      console.error('GEMINI_API_KEY not configured');
      return new Response(
        JSON.stringify({ error: 'AI service not configured', code: 'CONFIG_ERROR' } as ErrorResponse),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Parse and validate request body (AC: 7)
    const body: EnhanceRequest = await req.json();

    if (!body.problem?.trim() || !body.solution?.trim() || !body.impact?.trim()) {
      return new Response(
        JSON.stringify({
          error: 'Missing required fields: problem, solution, impact',
          code: 'VALIDATION_ERROR',
        } as ErrorResponse),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate content length (prevent abuse)
    const totalLength = body.problem.length + body.solution.length + body.impact.length;
    if (totalLength > 10000) {
      return new Response(
        JSON.stringify({
          error: 'Content too long. Maximum 10,000 characters total.',
          code: 'CONTENT_TOO_LONG',
        } as ErrorResponse),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Call Gemini with retry logic (AC: 4, 5)
    const enhanced = await withRetry(() =>
      enhanceWithGemini(body.problem, body.solution, body.impact)
    );

    return new Response(JSON.stringify(enhanced), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Enhancement failed:', error);

    // Return clear error response (AC: 5)
    return new Response(
      JSON.stringify({
        error: 'Failed to enhance idea. Please try again or proceed with original text.',
        code: 'ENHANCEMENT_FAILED',
      } as ErrorResponse),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
