import { PRD_SECTIONS } from '../constants/prdSections';
import { PrdSectionViewer } from './PrdSectionViewer';
import { PrdTableOfContents } from './PrdTableOfContents';
import type { PrdContent } from '../types';

interface PrdDocumentViewProps {
  prdContent: PrdContent;
}

export function PrdDocumentView({ prdContent }: PrdDocumentViewProps) {
  return (
    <div className="flex gap-8">
      {/* Table of Contents (Desktop Sidebar) */}
      <aside className="w-48 flex-shrink-0">
        <PrdTableOfContents prdContent={prdContent} />
      </aside>

      {/* Main Document Content */}
      <article className="flex-1 min-w-0">
        {PRD_SECTIONS.map((section) => (
          <PrdSectionViewer
            key={section.key}
            sectionKey={section.key}
            section={prdContent[section.key]}
          />
        ))}

        {/* Print-only footer */}
        <footer className="hidden print:block mt-8 pt-4 border-t border-base-300 text-sm text-base-content/60">
          <p>Generated by IdeaSpark • {new Date().toLocaleDateString()}</p>
        </footer>
      </article>
    </div>
  );
}
